# 临时目录
temp_dir: "temp"

# 目录设置
directories:
  # 输入目录路径
  input: "D:/电子书/火影忍者"
  # 输出目录后缀（将添加到输入目录后）
  output_suffix: "_upscale"

# 超分辨率设置
upscale:
  # 使用的模型名称
  model_name: "RealESRGAN_RealESRGAN_x4plus_anime_6B_4x.pth"
  # 放大倍数
  scale: 4
  # 目标长边尺寸（适配电子墨水屏）
  target_long_edge: 1872
  # 并行处理的进程数
  num_processes: 4
  # 输出图片格式
  output_format: "JPEG"
  # 输出图片质量 (1-100)
  output_quality: 95

# EPUB设置
epub:
  # 是否调整到原始大小
  resize_to_original: false
  # 是否创建新的EPUB
  create_new: false
  # 是否创建适配电子墨水屏的EPUB
  create_eink: true 